---

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_version: "2.62"
jenkins_package_state: present

jenkins_install_dir: /var/lib/jenkins
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""
jenkins_admin_token: ""
jenkins_admin_token_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"

jenkins_plugins:
  - bitbucket
  - bitbucket-pullrequest-builder
  - build-pipeline-plugin
  - copyartifact 
  - credentials 
  - delivery-pipeline-plugin 
  - environment-script 
  - git
  - ghprb
  - greenballs 
  - hipchat 
  - junit 
  - matrix-auth 
  - matrix-project 
  - parameterized-trigger 
  - rebuild 
  - ssh
  - s3 
  - throttle-concurrents 
  - ace-editor
  - ant
  - antisamy-markup-formatter
  - authentication-tokens
  - bouncycastle-api
  - branch-api
  - build-timeout
  - cloudbees-folder
  - credentials
  - credentials-binding
  - display-url-api
  - docker-commons
  - docker-workflow
  - durable-task
  - email-ext
  - external-monitor-job
  - favorite
  - git
  - git-client
  - git-server
  - github
  - github-api
  - github-branch-source
  - github-organization-folder
  - gradle
  - handlebars
  - icon-shim
  - jackson2-api
  - javadoc
  - jquery-detached
  - junit
  - mailer
  - mapdb-api
  - matrix-auth	
  - matrix-project
  - maven-plugin
  - metrics
  - momentjs
  - pam-auth
  - pipeline-build-step
  - pipeline-github-lib
  - pipeline-graph-analysis
  - pipeline-input-step	
  - pipeline-milestone-step
  - pipeline-model-api
  - pipeline-model-declarative-agent	
  - pipeline-model-definition
  - pipeline-rest-api
  - pipeline-stage-step
  - pipeline-stage-tags-metadata
  - pipeline-stage-view
  - plain-credentials
  - pubsub-light
  - resource-disposer
  - scm-api
  - script-security
  - sse-gateway
  - ssh-credentials
  - ssh-slaves	
  - structs
  - subversion
  - timestamper
  - token-macro	
  - variant
  - windows-slaves
  - workflow-aggregator
  - workflow-api
  - workflow-basic-steps
  - workflow-cps
  - workflow-cps-global-lib
  - workflow-durable-task-step
  - workflow-job
  - workflow-multibranch
  - workflow-scm-step
  - workflow-step-api
  - workflow-support
  - ws-cleanup
  - CloudBees Docker Build and Publish plugin
  - Email Extension Template Plugin
  - Build Authorization Token Root Plugin
  - Slack Notification Plugin
  - GitHub plugin
